### ISSUE TITLE
Allow default export in wasm

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/esm-integration#12]
Following https://github.com/WebAssembly/esm-integration/issues/9#issuecomment-381110653.

```wat
(module
  (func (export "default"))
)
```

would be importable using the `ImportedDefaultBinding` in JS:

```js
import m from "./module.wasm";
```

**Comment by lukewagner** [comment]
This makes sense, since `default` is a keyword and thus otherwise, presumably, a load-time error (thrown either by the loader or wasm JS API).  Perhaps also for imports?

**Comment by littledan** [comment]
To summarize, is the idea of this thread, Wasm should be allowed to export the `"default"` identifier, but doesn't need any special syntax or semantics to support default exports beyond that?

**Comment by xtuc** [comment]
Yes, which will work with the current cjs/esm interop that calls `.default` for the esm default. Does it make sense to you?

**Comment by littledan** [comment]
@xtuc Yes, this sounds like a good plan to me.

**Comment by littledan** [comment]
Sounds like nothing to do here, `"default"` will work just fine.
