### ISSUE TITLE
Permit imports of Numbers as const globals?

### ISSUE THREAD

**Issue by littledan** [WebAssembly/esm-integration#16]
If something is not a WebAssembly.Global object, and it's imported with a numeric mutable global type, it makes sense to call this an error, since there's no way a live binding could be of just numeric type. I like the idea of making this possible with a combination of host bindings and `anyref`.

For const global numeric imports, though, if we take the strategy in #13, I don't see the problem with snapshotting them (after casting them to the right numeric type). Actually, if we did snapshot them, it'd be more consistent with how the JS API works, which implicitly creates const globals for Numbers which are passed into the API.

Thoughts?

**Comment by xtuc** [comment]
Yes, It's a type error.

What about:
```js
export let a = 1;
```

Since the value will be copied it won't be mutable, I hope that it won't create confusion for users.

**Comment by littledan** [comment]
@xtuc Yes, I can see how some people may expect a live binding rather than a snapshot. That's sort of a different, cross-cutting issue, though: functions are also proposed to have their semantics based on a snapshot, rather than a live binding. Also, if you replace one WebAssembly.Global object with another in your export, it's proposed that importing modules will still point to the original one. Overall, supporting live bindings by default would lead to significant additional complexity for WebAssembly semantics (what would it mean for Tables and Memory?!).

**Comment by xtuc** [comment]
The thing is that user won't keep a handle on a bare number export, as opposed to WebAssembly.{Table,Memory,Global}.

If i'm not mistaken, 

```js
export let a = 1;
a = 2;
```

will snapshot a constant 2, but they won't be able to mutate it after.

```js
export let a = 1;
export function t() {
  a = 2;
}
```

This has no precedence in JS (that i'm aware of at least) and I think that it will confuse some users.

**Comment by littledan** [comment]
Bindings are not live in these semantics for functions either. Do you think that will be confusing?
