### ISSUE TITLE
Circular imports of functions as a host-bindings follow-on?

### ISSUE THREAD

**Issue by littledan** [WebAssembly/esm-integration#17]
Thanks to @xtuc and @sokra, webpack supports WebAssembly modules. We're [currently discussing](https://github.com/webpack/webpack/issues/8144) how to align webpack and the new specification in this repository.

One interesting thing about webpack is that (if I understand correctly) it supports cyclic Wasm modules importing globals and functions, rewriting parts of the code to implement live bindings.

Webpack implements these circular imports on top of the Wasm/JS API, so it's doing it without interrupting the Wasm instantiate path. I believe that's just the invariant we need we need in order to make type imports work.

As an MVP, I think it's OK to leave out circular Wasm modules, but I'd like to go about this design thinking about enabling some limited use of circular modules as a follow-on proposal. It would still be based on, modules are instantiated one by one, separately, but if you mark an import as "circular" with host bindings, then an extra snippet is generated to create a function that throws an exception, until the other module is loaded, and then it forwards to that other function.

Thoughts?

**Comment by xtuc** [comment]
> [...] rewriting parts of the code to implement live bindings.

They are really live bindings, we pass the values once the module has been instantiated. Here's one example https://github.com/webpack/webpack/issues/6433#issuecomment-372232238.

**Comment by littledan** [comment]
@xtuc I see, thanks for explaining. Is that how Wasm function imports work too?

**Comment by xtuc** [comment]
That's more or less a side-effect, but yes.

IRC a circular import with the same module is in discussion somewhere (maybe for threads, I can't remember) and that would be possible in Webpack.
