### ISSUE TITLE
Nit: What should we use the term "live binding" for?

### ISSUE THREAD

**Issue by littledan** [WebAssembly/esm-integration#19]
I originally thought "live binding" referred to a mutable variable storage, which could be exported, and then overwriting the variable on one end would affect the live binding on the other end.

The README in this repository, and under #13, seems to use "live binding" to mean something else: when wasm exports something (e.g., a Global, Memory, or Table) which is somehow mutable, then the binding is "live" in the sense that, when that object is mutated, it's reflected in the exported version. This usage was initially surprising to me; I would've thought of this as a kind of snapshot (just a shallow one, of a mutable object)

I'd suggest that, in this proposal, we either clarify that we're using this broader sense of "live binding" (could be just a couple sentences), or avoid the term.

**Comment by xtuc** [comment]
I think that a mutable Object is a better term, whereas live binding would implit a direct memory access? 

The WebAssembly spec doesn't mention "live binding", we should avoid introducing it here.

**Comment by sendilkumarn** [comment]
But specifying `mutable Object` will give an impression of an object is mutable in two ways (both via JS and WASM). I think it is a thin line here

**Comment by xtuc** [comment]
Well, for `WebAssembly.Memory` or `WebAssembly.Global` (mutable) that's how they work.

**Comment by sendilkumarn** [comment]
yeah, I agree, but that does not include everything right?

**Comment by sendilkumarn** [comment]
I think yes. since `WebAssembly.Tables` are mutable in JS world.

**Comment by xtuc** [comment]
This thing is that from a JS perceptive (unless it's readonly) a WebAssembly func (HostFunc) is a mutable object, right?

I think we should just avoid the term "live binding" and call the communication surface: API.

**Comment by littledan** [comment]
Yes, it's true, and the Wasm/JS API guarantees that the host functions are shared when being re-exported multiple times.

**Comment by sendilkumarn** [comment]
@xtuc does it means that I can override the `HostFunc` in JS with something else and it will be updated is it?

**Comment by sendilkumarn** [comment]
>  that the host functions are shared

Yeah, they are shared. Are they mutable?

**Comment by littledan** [comment]
Yes, they are ordinary mutable JS objects.
