### ISSUE TITLE
Imported memory and shared imported memory

### ISSUE THREAD

**Issue by Arnavion** [WebAssembly/esm-integration#3]
If multiple relocatable WASM modules import memory instead of exporting it, a post-processor / linker / loader can relocate them so that they can use different parts of the same imported memory. This means that at runtime, values placed into this common memory can be directly accessed by multiple WASM modules, whereas with each module exporting its own memory some code in the host environment (ie userland JS) has to get involved and copy values around.

I imagine that relocatable, memory-importing modules will be a good way to ship binary-only modules in the future, when relocation and linking are stabilized in the WASM spec.

So there are a few related questions (which can be split up into multiple issues if you want):

- How would a WASM module that wants to import memory work with the ESM `import` statement?

- How would a module graph that wants to use the same imported memory for multiple modules do that with the ESM `import` statement?

- Would there be a way to hook into the module-import mechanism so that a linker/loader implemented in userland JS can post-process a relocatable module into a relocated one if the module is imported with the ESM `import` statement? (Perhaps the answer to this is "It won't; you have to fall back to `instantiateStreaming`" or "Let's wait for relocation to be stabilized first".)

**Comment by jfbastien** [comment]
Some of these questions are good for the ESM integration repo, but some (like how global offset tables should work) are better addressed in https://github.com/WebAssembly/tool-conventions

**Comment by Arnavion** [comment]
There is no question about how relocation should work in general. I assume you're referring to the third question, which is about how relocation would work with the ESM `import` statement.

**Comment by jfbastien** [comment]
How a linker / loader works, and how they do relocations and offset tables within a shared memory, is something that we should discuss in the tool-conventions repo. Making sure it's possible at all is an ESM topic.

**Comment by Arnavion** [comment]
Yep. As I said, I'm not discussing how relocations should work in this issue.

**Comment by linclark** [comment]
> How would a WASM module that wants to import memory work with the ESM import statement?

In the initial version of ES module interop, you won't be able to create an import in JS and then import it to wasm. However, you will be able to export a memory from a wasm module and import it into another wasm module. You would also be able to re-export via JS, as follows:

```
// main.wasm
(module
  (import "./a.js" "memoryExport" (memory 0))
)

// a.js
export {memoryExport} from "./b.wasm";

// b.wasm
(module
  (memory 1)
  (export "memoryExport" (memory 0))
)
```

> How would a module graph that wants to use the same imported memory for multiple modules do that with the ESM import statement?

In the example above, we could have multiple modules which import `memoryExport` from `b.wasm`.

> Would there be a way to hook into the module-import mechanism so that a linker/loader implemented in userland JS can post-process a relocatable module into a relocated one if the module is imported with the ESM import statement? (Perhaps the answer to this is "It won't; you have to fall back to instantiateStreaming" or "Let's wait for relocation to be stabilized first".)

As far as I'm aware, there hasn't yet been any suggestion of adding hooks into the module import mechanism. When in execution order would this post-processing need to happen? Is it possible that the exporting module could do it in its `start` function? That would run before the `start` function for any of the modules that import the memory.

**Comment by Arnavion** [comment]
@linclark 

>`(import "./a.js" "memoryExport" (memory 0))`

I can see how this would work if the module explicitly asked for memory to be imported from `a.js`. However I was asking about the kind of imported memory that already exists today for WASM modules (for example from using `lld --import-memory` to compile to WASM):

`(import "env" "memory" (memory $env.memory 1))`

How would the ES `import` statement import such a WASM module?

It would be quite unfortunate if the WASM module has to hard-code the path of a specific ES module to import memory from. I see the benefit of importing memory to be that multiple independently-sourced modules can operate on the same memory without needing the host environment to copy bits around.

Perhaps `env.memory` is an arbitrary convention chosen by LLVM, so maybe one solution is that everyone instead standardizes on `./memory.js` even though it would look strange on non-ES host environments.

**Comment by littledan** [comment]
This proposal supports importing and exporting Memory, to and from both JS and Wasm. Further discussion about conventions on top can happen in https://github.com/WebAssembly/tool-conventions .
