### ISSUE TITLE
ESM isn't suited for importing objects containing non-JavaScript identifiers

### ISSUE THREAD

**Issue by 00ff0000red** [WebAssembly/esm-integration#39]
Example:
A JavaScript module imports a Wasm module, the Wasm module is as follows:
```wat
(func (export "+") (param f64 f64) (result f64)
    local.get 0
    local.get 1
    f64.add
)
```
How does JavaScript import that?

Yes, ESM allows renaming imports, but it doesn' not allow surrounding them with quotes or something that would allow any name to be imported and renamed.

Currently, this would result in a syntax error:

```js
import { "+" as add } from "./module.wasm";
```

How would this be handed?

**Comment by devsnek** [comment]
We are adding this exact functionality to JS: https://github.com/tc39/ecma262/pull/2154

**Comment by 00ff0000red** [comment]
> We are adding this exact functionality to JS: [tc39/ecma262#2154](https://github.com/tc39/ecma262/pull/2154)

Oh perfect, beat me to it.
It seems to have already passed the proposal stage and is already being worked on implementation?
If so, I'll close this issue as it is no longer true.

**Comment by ExE-Boss** [comment]
You can already do, which is what I’d presume transpilers might do:
```js
import * as _module_wasm from "./module.wasm";
```

And then instead of `add`, you’d use `_module_wasm["+"]`.
