### ISSUE TITLE
Does this proposal support `*` and `as` in wasm imports?

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/esm-integration#67]
In JavaScript, `import * as name from module_name` is supported, and I found that `import module_name name importdesc` is allowed in this proposal, so I wonder does this proposal support `*` and `as` in wasm imports?

**Comment by Phosra** [comment]
I really just creates a mapping from Wasm to JS import/export names. JS won't know whether it's importing from Wasm or JS or something new and entirely different, just that it's receiving strings or identifiers.

In fact, Wasm allows arbitrary UTF-8 strings as import and export "names" – in that case, you *have* to (be able to) use `as` from JS:
```wat
;; main.wasm
(func (export "+") (param f64 f64) (result f64)
 local.get 0
 local.get 1
 f64.add
)
```
```js
// main.mjs
import { "+" as add } from "./main.wasm";

console.assert(
 4.0 === add(1.5, 2.5),
 `"+" isn't an addition function`
);
```

**Comment by Phosra** [comment]
> In JavaScript, `import * as name from module_name` is supported, and I found that `import module_name name importdesc` is allowed in this proposal, so I wonder does this proposal support `*` and `as` in wasm imports?

Or wait, had I misunderstood you?
Are you asking whether Wasm may import from JS/Wasm, and rename them? In this case, it's a non-issue because Wasm doesn't use the import name as-is, instead of uses internal debug identifiers, which map to Brujin indexing, or just directly use those indexes.
```js
// main.mjs
export function add(x, y) {
 return x + y;
}
```
```wat
;; main.wasm
(import "./main.mjs" "add"
 (func $some_foreign_function
  (param f64 f64)
  (result f64)
 )
)
;; the name is "some_foreign_function;" it's index is zero (0)
;; it *could* have been $add to name it "add" but it only would've been the same as the import string by conscious decision
```

**Comment by Phosra** [comment]
> 1. For `as`, I think that if there is an exported function in `add.mjs`:  
>   ```javascript
>   // add.mjs
>   export function add(x, y) {
>       return x + y;
>   }
>   ```
>   - in javascript file `main.mjs`, the following code would work, which will rename `add` to `addTwoNumber`.
>   ```javascript
>   // main.mjs
>   import {add as addTwoNumber} from "./add.mjs"
>   ``` 
>   - in webassembly file `main.wasm`, the follwing code would work, which will rename `add` to `addTwoNumber` too. 
>   ```
>   (import "./add.mjs" "addTwoNumber" (func $add (param i32, param i32)(result i32)))
>   ```    
>   Is my understanding correct?

the key was that
> ...it's a non-issue, because Wasm doesn't use the import name as-is, instead of uses internal debug identifiers...

The name to import is strictly `add`.
If one is developing a compiler, or using the raw wat text, or wasm, then you could *name* (not __re__name) it `addTwoNumber`, like so:
```wat
(import "./add.mjs" "add" (func $addTwoNumber (param i32 i32) (result i32)))
```
or export it under a different name:
```wat
(import "./add.mjs" "add" (func $add (param i32 i32) (result i32)))
(export "addTwoNumber (func $add))
```

**Comment by yviansu** [comment]
@Phosra I got it! Thanks a lot! 

And the issue can be closed.
