### ISSUE TITLE
Proposal overview should include examples of `import source`

### ISSUE THREAD

**Issue by ajklein** [WebAssembly/esm-integration#80]
`import source` is mentioned in the note in the root [README](../blob/main/README.md) as something that engines could support without fully implementing this proposal. But there are no examples in either the [main overview](https://github.com/WebAssembly/esm-integration/blob/main/proposals/esm-integration/README.md) or the [examples](https://github.com/WebAssembly/esm-integration/blob/main/proposals/esm-integration/EXAMPLES.md) about what this would look like. Such examples would be very helpful in understanding all that's enabled by this proposal.

**Comment by guybedford** [comment]
Thanks for mentioning this, I just got a new readme PR up in https://github.com/WebAssembly/esm-integration/blob/ac3a2f9f2e683b6f75e862af0b8da5af06ac0d8c/proposals/esm-integration/README.md which should resolve this. Let me know if you find any further clarification missing.
