### ISSUE TITLE
Disallow imported default in wasm

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/esm-integration#9]
Currently we don't allow the user to import a default export, the syntax and the ImportObject ensures that:

```wat
(import "./module.js" "specifier" (func))
```

**My opinion** is that it's fine and otherwise would add unnecessarily complexity to the semantics/integration. We need to make it clear in the documentation because JavaScript permits it and uses it in distributed modules.

On a side note, we should disallow default exports in wasm as well. There would be no way to distinguish a named "default" export and a default export.

**Comment by guybedford** [comment]
The default import is just the "default name" in ES modules. So I don't think this is a concern for wasm as `(import "./module.js" "default" (func))` should be fine.

**Comment by xtuc** [comment]
That's correct, but wasm could export a named "default". I just want to remove any confusion for users.

**Comment by guybedford** [comment]
Could you clarify the confusion? Surely `import x from './x.wasm'` is useful?

**Comment by xtuc** [comment]
Ah I see, you mean that the named "default" export in wasm would be the default import in ESM?

**Comment by guybedford** [comment]
Yes exactly, the default import is just the "default" name, there's nothing special about it apart from some sugar syntax.

**Comment by xtuc** [comment]
I created https://github.com/WebAssembly/esm-integration/issues/12 to track it.

so to be consistent, the default export could be imported using:

```wat
(import "./module.js" "default" (func))
```

**Comment by littledan** [comment]
To summarize, is the idea of this thread, nothing special should be done for default imports, and they should just be imported using the `"default"` specifier? If so, that sounds good to me.

**Comment by xtuc** [comment]
It's unclear to me if it will import a named exports call `default` or the actual default export. Since it's just a StringLiteral and not a keyword, it will call the named export.

The issue is that it's not possible to import the default export then.

**Comment by littledan** [comment]
@xtuc I'm not sure what difference you're getting at. I thought that default exports were represented by a `default` name, both on the export and import side, so it seems like everything would just match up. Maybe I'm misunderstanding, though.

**Comment by xtuc** [comment]
I forgot that you can't export a named export called `default`, like the following:
```js
export function default() {}
```

That's a syntax error in JS (what does it means for other languages that might allow it, I don't' know). I guess my last point is invalid.

My request is a clarification, should it import the default export or a named export?

**Comment by littledan** [comment]
I think WebAssembly should always refer to named imports and exports, and use the name `default`.

**Comment by littledan** [comment]
I don't see anything to change about this proposal; I think we should continue to allow `"default"` imports and exports to work just fine with JavaScript. Therefore, I'm closing this issue.
